# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"
#ZSH_THEME="candy"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
 DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
#plugins=(git colored-man common-aliases git-flow github screen autojump)
plugins=(git autojump)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
export PATH=$PATH:/opt/homebrew/bin/:/usr/local/Cellar/php/5.3.10/bin/:/Applications/SenchaSDKTools-2.0.0-Beta/jsbuilder:/Applications/SenchaSDKTools-2.0.0-Beta/bin:/Applications/SenchaSDKTools-2.0.0-Beta:/Users/zhqm03/bin:/Users/zhqm03/local/bin:/Applications/SenchaSDKTools-2.0.0-Beta/jsbuilder:/Applications/SenchaSDKTools-2.0.0-Beta/bin:/Applications/SenchaSDKTools-2.0.0-Beta:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11/bin:/Users/zhqm03/workspace/android-sdk/tools:/Users/zhqm03/workspace/android-sdk/platform-tools:/Users/zhqm03/bin:/Users/zhqm03/workspace/android-sdk/tools:/Users/zhqm03/workspace/android-sdk/platform-tools
export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"


PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting


if [ -f ~/.bash_alias ]
then
    . ~/.bash_alias
fi
if [ -f ~/.bash_profile ]
then
    . ~/.bash_profile
fi
export CLICOLOR=1
export PATH="/opt/homebrew/opt/sqlite/bin:$PATH"
export GEMINI_API_KEY="AIzaSyAk7etmrZnQxi9D3tARPy4kM4lxoEHjsMA"

export GOPATH=$HOME/go
# 对于 Apple Silicon Mac (M1/M2 芯片)，GOROOT 可能是 /opt/homebrew/lib/go 或 /opt/homebrew/opt/go/libexec
export GOROOT=/opt/homebrew/opt/go/libexec
# 对于 Intel Mac，GOROOT 可能是 /usr/local/lib/go 或 /usr/local/opt/go/libexec[1](@ref)
# export GOROOT=/usr/local/opt/go/libexec
export PATH=$PATH:$GOPATH/bin:$GOROOT/bin

# pnpm
export PNPM_HOME="/Users/kufazhang/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end


# Added by CodeBuddy CN
export PATH="/Users/kufazhang/.codebuddy/bin:$PATH"


# Added by CodeBuddy
export PATH="/Users/kufazhang/.codebuddy/bin:$PATH"
export PATH="$PATH:$HOME/.ft"
source ~/.env
export PATH="/opt/homebrew/opt/mysql-client/bin:$PATH"
export ENABLE_LSP_TOOL=1

# OpenClaw Completion
source <(openclaw completion --shell zsh)

export PATH="/Users/kufazhang/background_agent_cli/bin:$PATH" # background_agent_cli PATH
